name: trans_all_common_internationalization
description: Internationalized strings used across Karibu apps.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter

  # Package for logging debug and error messages.
  logging: ^1.0.1

  # A flutter package to manage the state.
  get: ^4.6.5

  karibu_capital_core_internationalization:
    git:
      url: https://nidovic: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@github.com/karibu-cap/flutter_core.git
      ref: 272ae8e
      path: internationalization
    
  karibu_capital_core_static_analysis:
    git:
      url: https://nidovic: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@github.com/karibu-cap/flutter_core.git
      ref: 272ae8e
      path: static_analysis

dev_dependencies:
  flutter_test:
    sdk: flutter
