name: trans_all_common_internationalization
description: Internationalized strings used across Karibu apps.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: "3.3.1"
  flutter: "3.19.3"

dependencies:
  flutter:
    sdk: flutter

  # Package for logging debug and error messages.
  logging: ^1.0.1

  # A flutter package to manage the state.
  get: ^4.6.5

  karibu_capital_core_internationalization:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: internationalization

  karibu_capital_core_static_analysis:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: static_analysis

dev_dependencies:
  flutter_test:
    sdk: flutter
