name: trans_all_common_models
description: Representation of TransAll database structures.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: "3.3.1"
  flutter: "3.19.3"

dependencies:
  flutter:
    sdk: flutter

  # Common static analysis options.
  karibu_capital_core_static_analysis:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
