name: trans_all_common_config
description: Common configuration options among TransAll apps.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: "3.3.1"
  flutter: "3.19.3"

dependencies:
  # Used to add annotations to various functions.
  meta: ^1.3.0

  karibu_capital_core_remote_config:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: remote_config
  karibu_capital_core_database:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: database

  trans_all_common_utils:
    path: ../../common/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Common static analysis options.
  karibu_capital_core_static_analysis:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
