#!/usr/bin/python
import dependencies as deps

deps.chdir('./app_customers')

# Run the dart format test script
dartTest = deps.run('flutter format --dry-run --set-exit-if-changed .')

# Returns the exit code returned by the dart format test Script
exit(dartTest.returncode)