// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import '../firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev implements FirebaseOptionsInterface {
  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'AIzaSyBxwFW1E4Y3Thjy_n6XJxZLHFqzHBjB1yk',
    appId: '1:812086350186:web:d5d63027d5acc8560a1513',
    messagingSenderId: '812086350186',
    projectId: 'transtu-dev',
    authDomain: 'transtu-dev.firebaseapp.com',
    storageBucket: 'transtu-dev.appspot.com',
    measurementId: 'G-4BJ14E377M',
  );

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyA63XXqXfcGeO4FwZl-8d96vRRupiy_vsk',
    appId: '1:812086350186:android:e423bcabb0c38a420a1513',
    messagingSenderId: '812086350186',
    projectId: 'transtu-dev',
    storageBucket: 'transtu-dev.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4-jW8uA-9Pm9LPKxq62MHvObVyxsEJE',
    appId: '1:812086350186:ios:8c573120d438a55e0a1513',
    messagingSenderId: '812086350186',
    projectId: 'transtu-dev',
    storageBucket: 'transtu-dev.appspot.com',
  );

  static FirebaseOptions get _currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  @override
  FirebaseOptions getOptions() {
    return _currentPlatform;
  }
}
