// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import '../firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd implements FirebaseOptionsInterface {
  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'AIzaSyAGeip_vCNB9Pjz4-Ja38y2Z5G791Bgoio',
    appId: '1:797230719116:web:e3eba7758dda019015dba9',
    messagingSenderId: '797230719116',
    projectId: 'transtu-prod',
    authDomain: 'transtu-prod.firebaseapp.com',
    storageBucket: 'transtu-prod.appspot.com',
    measurementId: 'G-GMV997TKYR',
  );

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyDTWMbi1T1OlKDfLl2p9nb9YDdFeBEXCqM',
    appId: '1:797230719116:android:7ba50cf1cb7601ed15dba9',
    messagingSenderId: '797230719116',
    projectId: 'transtu-prod',
    storageBucket: 'transtu-prod.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyAbgnuIDbFo50bcQEUEfJE430JRkpUy_zU',
    appId: '1:797230719116:ios:cfb6265e79b2fcec15dba9',
    messagingSenderId: '797230719116',
    projectId: 'transtu-prod',
    storageBucket: 'transtu-prod.appspot.com',
  );

  static FirebaseOptions get _currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  @override
  FirebaseOptions getOptions() {
    return _currentPlatform;
  }
}
