name: trans_all_common_utils
description: Representation of TransAll common utility functions.
version: 1.0.0
homepage: none
publish_to: none

environment:
  sdk: "3.3.1"
  flutter: "3.19.3"

dependencies:
  # Core crash reporting.
  karibu_capital_core_crash_reporting:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: crash_reporting

  # Common static analysis options.
  karibu_capital_core_static_analysis:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: main
      path: static_analysis

  # Provides an API for querying information about an application package.
  # Platform: ANDROID, IOS, LINUX, MACOS, WEB, WINDOWS, SERVER
  package_info_plus: ^6.0.0

  # Provides APIs for debugging and error logging, similar to loggers in other languages,
  # such as the Closure JS Logger and java.util.logging.Logger.
  # Platform: ANDROID, IOS, LINUX, MACOS, WEB, WINDOWS, SERVER
  logging: 1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
