name: trans_all_common_utils
description: Representation of TransAll common utility functions.
version: 1.0.0
homepage: none
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ^3.10.6

dependencies:
  # Core crash reporting.
  karibu_capital_core_crash_reporting:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: 272ae8e
      path: crash_reporting
    

  # Common static analysis options.
  karibu_capital_core_static_analysis:
    git:
      url: https://github.com/karibu-cap/flutter_core.git
      ref: 272ae8e
      path: static_analysis
  
  # Plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  # Platform: ANDROID, IOS, MACOS, WEB
  firebase_core: 2.13.0

  # Provides an API for querying information about an application package.
  # Platform: ANDROID, IOS, LINUX, MACOS, WEB, WINDOWS, SERVER
  package_info_plus: 3.0.3

  # Provides APIs for debugging and error logging, similar to loggers in other languages,
  # such as the Closure JS Logger and java.util.logging.Logger.
  # Platform: ANDROID, IOS, LINUX, MACOS, WEB, WINDOWS, SERVER
  logging: 1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
