name: Customer Deployment APP (STAGING)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"

# Ensure that only one staging workflow runs at a time.
concurrency:
  group:  app-customer-deployment-staging
  cancel-in-progress: true

jobs:
  staging:
    uses: ./.github/workflows/app_customers_deployment_base.yml
    with:
      TRANSTU_APP_ENVIRONMENT: staging
      TRANSTU_APP_NAME_PLACE_CUSTOMERS: TransAll.STAGING
      UPLOAD_TO_PLAY_STORE_CUSTOMERS: false
      TRANSTU_ANDROID_APP_ID_CUSTOMERS: 1:210743853862:android:7dc9e6f3c606a4b9c977e7
      TRANSTU_USE_ANDROID_APP_BUNDLE: false
      TRANSTU_USE_ANDROID_APP_APK: true
    secrets:
      TRANSTU_UPLOAD_KEYSTORE_PROPERTIES_BASE64: ${{ secrets.TRANSTU_UPLOAD_KEYSTORE_PROPERTIES_BASE64 }}
      TRANSTU_UPLOAD_KEYSTORE_JKS_BASE64: ${{ secrets.TRANSTU_UPLOAD_KEYSTORE_JKS_BASE64 }}
      GOOGLE_PLAY_STORE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_PLAY_STORE_CREDENTIALS_BASE64 }}
      TRANSTU_FIREBASE_CLI_TOKEN: ${{ secrets.TRANSTU_FIREBASE_CLI_TOKEN }}
